// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session_03.Inheritance.Context;

#nullable disable

namespace Session_03.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240916140600_ update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Session_03.Inheritance.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Session_03.Inheritance.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("Session_03.Inheritance.Models.Employee");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.ToTable("FullTimeEmployees", (string)null);
                });

            modelBuilder.Entity("Session_03.Inheritance.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("Session_03.Inheritance.Models.Employee");

                    b.Property<double>("HourRate")
                        .HasColumnType("float");

                    b.Property<int>("NumbersOfHours")
                        .HasColumnType("int");

                    b.ToTable("PartTimeEmployees", (string)null);
                });

            modelBuilder.Entity("Session_03.Inheritance.Models.FullTimeEmployee", b =>
                {
                    b.HasOne("Session_03.Inheritance.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Session_03.Inheritance.Models.FullTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Session_03.Inheritance.Models.PartTimeEmployee", b =>
                {
                    b.HasOne("Session_03.Inheritance.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Session_03.Inheritance.Models.PartTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
